[package]
name = "data-test-abi"
version = "0.0.0"
authors = [ "Suda Eduardo <arikiueda@gmail.com>",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.data-test]
path = ".."

[dependencies.elrond-wasm]
version = "0.13.0"

[dependencies.elrond-wasm-debug]
version = "0.13.0"
